.catalog:
  name: Gitlab
  version: 8.16.1-ce.0
  questions: #Used to request user input for configuration options
    # - variable: "gitlab_host"
    #   type: "string"
    #   required: true
    #   label: "hostname for gitlab installation"
    # - variable: "gitlab_secrets_db_key_base"
    #   type: "password"
    #   required: true
    #   label: "secret key for gitlab installation(please save it somewhere)"
    # - variable: "gitlab_smtp_user"
    #   type: "string"
    #   required: true
    #   label: "Gmail user to send emails from"
    # - variable: "gitlab_smtp_pass"
    #   type: "password"
    #   required: true
    #   label: "Gmail password"
    # - variable: "gitlab_root_email"
    #   type: "string"
    #   required: true
    #   label: "ROOT user email"
    # - variable: "gitlab_root_password"
    #   type: "password"
    #   required: true
    #   label: "ROOT user password"
