version: '2'
gitlab-postgresql:
  environment:
    POSTGRES_DB: gitlabhq_production
    POSTGRES_USER: gitlab
    POSTGRES_PASSWORD: password
    PGDATA: /data/postgres/data
  image: postgres:9.5-alpine
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  stdin_open: true
  volumes:
  - gitlab_postgres_data:/data/postgres/data
gitlab-redis:
  image: redis:3.2.0-alpine
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  stdin_open: true
gitlab:
  image: sameersbn/gitlab:8.15.2
  stdin_open: true
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  environment:
    GITLAB_HTTPS: '${gitlab_ssl_true}'
    GITLAB_PORT: 4444
    SMTP_USER: '${gitlab_smtp_user}'
    SMTP_PASS: '${gitlab_smtp_pass}'
    GITLAB_HOST: '${gitlab_host}'
    GITLAB_ROOT_PASSWORD: '${gitlab_root_password}'
    GITLAB_ROOT_EMAIL: '${gitlab_root_email}'
    GITLAB_SECRETS_DB_KEY_BASE: '${gitlab_secrets_db_key_base}'
    GITLAB_SECRETS_SECRET_KEY_BASE: '${gitlab_secrets_db_key_base}'
    GITLAB_SECRETS_OTP_KEY_BASE: '${gitlab_secrets_db_key_base}'
  ports:
  - 4444:80/tcp
  links:
  - gitlab-postgresql:postgresql
  - gitlab-redis:redisio
  volumes:
  - gitlab_data:/home/git/data
