version: '2'
services:
  firefly-db:
    image: 'mysql:8'
    environment:
      - MYSQL_DATABASE=firefly_db
      - MYSQL_USER=firefly_db
      - MYSQL_PASSWORD=firefly_db_secret
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ${instance_label}_firefly-storage:/var/lib/mysql

  firefly-app:
    image: 'jc5x/firefly-iii'
    environment:
      - FF_DB_HOST=firefly-db
      - FF_DB_NAME=firefly_db
      - FF_DB_USER=firefly_db
      - FF_DB_PASSWORD=firefly_db_secret
      - FF_APP_KEY=SomeRandomStringOf32CharsExactly
      - FF_APP_ENV=local
      - SITE_OWNER=eugene@lifeisgoodlabs.com
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_FROM=vasyl@lifeisgoodlabs.com
      - MAIL_USERNAME=vasyl@lifeisgoodlabs.com
      - MAIL_PASSWORD=secret2005
      - MAIL_ENCRYPTION=tls
    ports:
      - - ${firefly_port}:80/tcp
    links:
      - firefly-db
    volumes:
      - ${instance_label}_firefly-app-storage:/var/www/firefly-iii/storage
