version: '2'
services:
  db:
    image: mysql/mysql-server:5.6
    volumes:
    - ${instance_label}_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: paSSw0rd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - ${wordpress_phpmyadmin_port}:80/tcp
    links:
    - db:db
  wordpress:
    image: wordpress:php5.6
    environment:
      WORDPRESS_DB_PASSWORD: paSSw0rd
    ports:
    - ${wordpress_port}:80/tcp
    links:
    - db:mysql
    volumes:
    - ${instance_label}_wordpress_data:/usr/src/wordpress
