db:
  image: mysql/mysql-server:5.6
  volumes:
  - $${stack_name}_mysql_data:/var/lib/mysql
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  stdin_open: true
  environment:
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: secretword
    MYSQL_ROOT_PASSWORD: paSSw0rd
phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  stdin_open: true
  ports:
  - ${wordpress_phpmyadmin_port}:80/tcp
  links:
  - db:db
wordpress:
  image: wordpress:php5.6
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  stdin_open: true
  environment:
    WORDPRESS_DB_USER: wordpress
    WORDPRESS_DB_PASSWORD: secretword
  ports:
  - ${wordpress_port}:80/tcp
  links:
  - db:mysql
  volumes:
  - $${stack_name}_wordpress_data:/usr/src/wordpress
