mysql:
  image: mysql/mysql-server:5.7
  volumes:
  - mysql_data:/var/lib/mysql
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  stdin_open: true
  environment:
    MYSQL_USER: wordpress
    MYSQL_ROOT_PASSWORD: secretword
phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  stdin_open: true
  ports:
  - ${wordpress_phpmyadmin_port}:80/tcp
  links:
  - mysql:db
wordpress:
  image: wordpress:php5.6
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  stdin_open: true
  environment:
    WORDPRESS_DB_USER: wordpress
    WORDPRESS_DB_PASSWORD: secretword
  ports:
  - ${wordpress_port}:80/tcp
  links:
  - mysql:mysql
  volumes:
  - wordpress_data:/usr/src/wordpress
