version: '2'
services:
  mysql:
    image: mysql
    volumes:
    - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
  phpmyadmin:
    image: docker pull phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    links:
      - mysql
  wordpress:
    image: wordpress:php7.0-fpm
    links:
      - mysql:db
    volumes:
      wordpress_data:/usr/src/wordpress
