.catalog:
  name: Initial version # Name of the versioned template of the Catalog Entry
  version: 0.1 # Version of the versioned template of the Catalog Entry
  description: installs wordpress with mysql and phpmyadmin # Description of the versioned template of the Catalog Entry
  minimum_rancher_version: 1.2 # The minimum version of Rancher that supports the template, v1.0.1 and 1.0.1 are acceptable inputs
  maximum_rancher_version: # The maximum version of Rancher that supports the template, v1.0.1 and 1.0.1 are acceptable inputs
  upgrade_from: # The previous versions that this template can be upgraded from
  questions: #Used to request user input for configuration options
  - variable: mysql_root_password # A single word that is used to pair the question and answer.
      label: Mysql Root Password # The "question" to be answered.
      description: |
      type: password
