.catalog:
  name: Initial version # Name of the versioned template of the Catalog Entry
  version: 0.1 # Version of the versioned template of the Catalog Entry
  description: installs wordpress with mysql and phpmyadmin # Description of the versioned template of the Catalog Entry
  minimum_rancher_version: 1.2 # The minimum version of Rancher that supports the template, v1.0.1 and 1.0.1 are acceptable inputs
