name: Wordpress under apache with mysql and phpmyadmin
description: |
  # Description of the Catalog Entry
version: 0.1 # Version of the Catalog to be used
category: wordpress # Category to be used for searching catalog entries
maintainer: # The maintainer of the catalog entry
license: # The license
projectURL: # A URL related to the catalog entry
